server:
  port: 8090

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      routes:

        # -------------------------
        # user-service 路由
        # -------------------------
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        # -------------------------
        # captcha-service
        # -------------------------
        - id: captcha-service
          uri: lb://captcha-service
          predicates:
            - Path=/captcha/**

        # -------------------------
        # product-service
        # -------------------------
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**

        # -------------------------
        # order-service - 订单接口
        # -------------------------
        - id: order-service-order
          uri: lb://order-service
          predicates:
            - Path=/order/**

        # -------------------------
        # order-service - 购物车接口
        # 分开写！否则会 404
        # -------------------------
        - id: order-service-cart
          uri: lb://order-service
          predicates:
            - Path=/cart/**
