server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      discovery:
        locator:
          # 自动根据服务名生成路由，服务名自动转为小写
          enabled: true
          lower-case-service-id: true

      routes:
        # user-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        # captcha-service
        - id: captcha-service
          uri: lb://captcha-service
          predicates:
            - Path=/api/captcha/**
          filters:
            - StripPrefix=1

        # product-service
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**

        # order-service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: cart-service
          uri: lb://order-service
          predicates:
            - Path=/cart/**

jwt:
  static-token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNzE0NDE2MDAwfQ.-hRAkTD14LdbEmUlvXxAxWp0ZIl9IvAY-OSiNLk8_Kk
  secret: secureSecretKey1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
  expiration: 86400000